[package]
name = "auto_chat"
version = "0.1.0"
authors = ["ben xie <benxie@3tech.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
